version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"             # Your PHP app
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      DB_NAME: eticket
    networks:
      - agri-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: eticket
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - agri-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9090:80"             # Access phpMyAdmin at http://localhost:9090
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
    networks:
      - agri-net

volumes:
  db_data:

networks:
  agri-net:
